SUSTAINING-949: add trivy scan to docker image creation workflow

diff --git a/.github/workflows/create-slackbot-docker-image.yml b/.github/workflows/create-slackbot-docker-image.yml
--- a/.github/workflows/create-slackbot-docker-image.yml
+++ b/.github/workflows/create-slackbot-docker-image.yml
@@ -34,6 +34,8 @@ jobs:
       IMAGE_NAME: "quay.io/ocp_sustaining_engineering/slack_backend"
       TAG_PATCH_VERSION: 0
       SLACKBOT_IMAGE_REPO_URL: "https://quay.io/api/v1/repository/ocp_sustaining_engineering/slack_backend/tag/"
+      QUAY_USERNAME: ${{ secrets.QUAY_REGISTRY_USERNAME }}
+      QUAY_PASSWORD: ${{ secrets.QUAY_REGISTRY_PASSWORD }}
 
     steps:
     - name: Validate inputs
@@ -104,9 +106,15 @@ jobs:
     - name: Mask Values and Login
       shell: bash
       run: |
-        QUAY_PASSWORD=$(jq -r '.inputs.quay_registry_password' $GITHUB_EVENT_PATH)
+        if ! QUAY_PASSWORD=$(jq -r '.inputs.quay_registry_password' $GITHUB_EVENT_PATH); then
+          echo "Failed to extract password"
+          exit 1
+        fi
         echo ::add-mask::$QUAY_PASSWORD
-        QUAY_USERNAME=$(jq -r '.inputs.quay_registry_username' $GITHUB_EVENT_PATH)
+        if ! QUAY_USERNAME=$(jq -r '.inputs.quay_registry_username' $GITHUB_EVENT_PATH); then
+          echo "Failed to extract username"
+          exit 1
+        fi
         echo ::add-mask::$QUAY_USERNAME
         echo "$QUAY_PASSWORD" | docker login quay.io -u $QUAY_USERNAME --password-stdin 2>/dev/null
 
@@ -154,6 +162,8 @@ jobs:
         context: .
         push: true
         tags: ${{ env.IMAGE_NAME }}:${{ env.NEXT_TAG_VERSION }}
+        cache-from: type=gha
+        cache-to: type=gha,mode=max
 
     - name: Check SARIF file contents
       if: always()
